apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: kamelet-telegram-source
  labels:
    app: kamelet-telegram-source
    app.kubernetes.io/instance: kamelet-telegram-source
    app.kubernetes.io/component: kamelet-telegram-source
    app.kubernetes.io/part-of: event-sources-app
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: telegram-source
    properties:
      authorizationToken: REPLACE ME
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: ordercheck
